/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import com.poly.helper.InPMStatic;
import com.poly.model.ChiTietPhieuMuon;
import com.poly.model.PhieuMuon;
import java.util.List;

/**
 *
 * @author hma20
 */
public class InPhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form InPhieuMuon
     */
    public InPhieuMuon() {
        initComponents();
        setLocationRelativeTo(null);
        inPM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInPM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInPhieuMuon = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnInPM.setText("In Phieu Muon");
        btnInPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInPMActionPerformed(evt);
            }
        });

        txtInPhieuMuon.setColumns(20);
        txtInPhieuMuon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtInPhieuMuon.setRows(5);
        jScrollPane1.setViewportView(txtInPhieuMuon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnInPM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInPM)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInPMActionPerformed
        // TODO add your handling code here:
        try {
            txtInPhieuMuon.print();
        } catch (Exception e) {
            Logger.getLogger(InPhieuMuon.class.getName()).log(Level.SEVERE, null, evt);
        }
        this.dispose();
    }//GEN-LAST:event_btnInPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InPhieuMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInPM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInPhieuMuon;
    // End of variables declaration//GEN-END:variables

    public void inPM() {
        PhieuMuon pm = InPMStatic.pm;
        List<ChiTietPhieuMuon> lists = InPMStatic.ctpm;
        txtInPhieuMuon.append("\t               Thong tin phieu muon\n\n");
        txtInPhieuMuon.append("  Ma phieu muon:  "+ pm.getMaPhieuMuon()+"\n");
        txtInPhieuMuon.append("  Sinh vien:      "+ pm.getMaSinhVien()+"\n");
        txtInPhieuMuon.append("  Nhan vien:      "+ pm.getMaNhanVien()+"\n");
        txtInPhieuMuon.append("  Ngay muon:      "+ pm.getNgayMuon()+"\n");
        txtInPhieuMuon.append("  Ngay tra:       "+ pm.getNgayTra()+"\n");
        txtInPhieuMuon.append("  Ghi chu:        "+ pm.getGhiChu()+"\n\n");
        txtInPhieuMuon.append("\t               Chi tiet phieu muon\n\n");
        txtInPhieuMuon.append("      STT\t\tMã sách\t\tSo luong\n");
        int i = 1;
        for(ChiTietPhieuMuon ctpm : lists){
        txtInPhieuMuon.append("     "+i+"\t\t"+ ctpm.getMaSach() +"\t\t"+ ctpm.getSoLuong() +"\n");
            i++;
        }
    }
}
