/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ui;

import com.poly.dao.PhieuMuonDAO;
import com.poly.helper.MsgBox;
import com.poly.helper.XDate;
import com.poly.model.ChiTietPhieuMuon;
import com.poly.model.PhieuMuon;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hma20
 */
public class QLPhieuMuonPanel extends javax.swing.JPanel {

    /**
     * Creates new form QLTheLoaiPanel
     */
    public QLPhieuMuonPanel() {
        initComponents();
        setTable();
        fillToTable();
        setMaSV();
        setMaNV();
        setNgayMuon();
        btnFirst.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPhieuMuon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        cboMaSV = new javax.swing.JComboBox<>();
        cboMaNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayMuon = new com.toedter.calendar.JDateChooser();
        txtNgayTra = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        rdoChuaTra = new javax.swing.JRadioButton();
        rdoDaTra = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCTPM = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cboSapXep = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuMuon = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnNhapDS = new javax.swing.JButton();
        btnInDS = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin PhieuMuon");

        jLabel2.setText("Ma phieu muon :");

        jLabel3.setText("Ma sinh vien :");

        jLabel4.setText("Ma nhan vien :");

        btnXoa.setText("Xoa");
        btnXoa.setPreferredSize(new java.awt.Dimension(90, 27));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.setPreferredSize(new java.awt.Dimension(90, 27));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnMoi.setText("Moi");
        btnMoi.setPreferredSize(new java.awt.Dimension(90, 27));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setText("Them");
        btnThem.setEnabled(false);
        btnThem.setPreferredSize(new java.awt.Dimension(90, 27));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngay muon :");

        jLabel6.setText("Ngay tra :");

        txtNgayMuon.setDateFormatString("dd/MM/yyyy");

        txtNgayTra.setDateFormatString("dd/MM/yyyy");

        jLabel7.setText("Trang thai :");

        btgGender.add(rdoChuaTra);
        rdoChuaTra.setText("Chua tra");

        btgGender.add(rdoDaTra);
        rdoDaTra.setText("Da tra");

        jLabel9.setText("Ghi chu :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thông Tin PhieuMuon");

        tblCTPM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblCTPM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhieuMuon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboMaSV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboMaNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoChuaTra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoDaTra)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2))))))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdoChuaTra)
                    .addComponent(rdoDaTra))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(610, 650));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Danh Sách Phieu Muon");
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 30));
        jPanel2.add(jLabel8);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 72));

        txtTimKiem.setPreferredSize(new java.awt.Dimension(300, 27));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/timkiem_black_24px.png"))); // NOI18N
        btnTimKiem.setPreferredSize(new java.awt.Dimension(40, 27));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));
        jPanel4.setPreferredSize(new java.awt.Dimension(190, 72));

        cboSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Tên thể loại tăng dần", "Tên thể loại giảm dần" }));
        cboSapXep.setPreferredSize(new java.awt.Dimension(160, 27));
        cboSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(575, 493));

        tblPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuMuon);

        jPanel2.add(jScrollPane1);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(585, 30));

        btnNhapDS.setText("Nhap DS");
        btnNhapDS.setPreferredSize(new java.awt.Dimension(90, 27));
        btnNhapDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDSbtnNhapDSActionPerformed(evt);
            }
        });

        btnInDS.setText("In DS");
        btnInDS.setPreferredSize(new java.awt.Dimension(90, 27));
        btnInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInDSbtnInDSActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLast.setText(">>");
        btnLast.setPreferredSize(new java.awt.Dimension(90, 27));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastbtnLastActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setText(">");
        btnNext.setPreferredSize(new java.awt.Dimension(90, 27));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextbtnNextActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPre.setText("<");
        btnPre.setPreferredSize(new java.awt.Dimension(90, 27));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrebtnPreActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFirst.setText("<<");
        btnFirst.setPreferredSize(new java.awt.Dimension(90, 27));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstbtnPreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNhapDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 610, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMuonMouseClicked
        // TODO add your handling code here:
        int index = tblPhieuMuon.getSelectedRow();
        loadForm(index);
    }//GEN-LAST:event_tblPhieuMuonMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (isCheckFormUpdate()) {
            update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (MsgBox.confirm(this, "Ban co chac chan muon xoa?")) {
            delete();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapDSbtnNhapDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDSbtnNhapDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapDSbtnNhapDSActionPerformed

    private void btnInDSbtnInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInDSbtnInDSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInDSbtnInDSActionPerformed

    private void btnLastbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastbtnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastbtnLastActionPerformed

    private void btnNextbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextbtnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextbtnNextActionPerformed

    private void btnPrebtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrebtnPreActionPerformed
        // TODO add your handling code here:
        previous();
    }//GEN-LAST:event_btnPrebtnPreActionPerformed

    private void btnFirstbtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstbtnPreActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstbtnPreActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        timKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cboSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSapXepActionPerformed
        // TODO add your handling code here:
        if (cboSapXep.getSelectedIndex() == 0 || cboSapXep.getSelectedIndex() == -1) {
            fillToTable();
        } else if (cboSapXep.getSelectedIndex() == 1) {
            sapXep1();
        } else if (cboSapXep.getSelectedIndex() == 2) {
            sapXep2();
        }
    }//GEN-LAST:event_cboSapXepActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (isCheckForm()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGender;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInDS;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNhapDS;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaNV;
    private javax.swing.JComboBox<String> cboMaSV;
    private javax.swing.JComboBox<String> cboSapXep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoChuaTra;
    private javax.swing.JRadioButton rdoDaTra;
    private javax.swing.JTable tblCTPM;
    private javax.swing.JTable tblPhieuMuon;
    private javax.swing.JTextArea txtGhiChu;
    private com.toedter.calendar.JDateChooser txtNgayMuon;
    private com.toedter.calendar.JDateChooser txtNgayTra;
    private javax.swing.JTextField txtPhieuMuon;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel modelPM, modelCTPM;
    PhieuMuonDAO pmDAO = new PhieuMuonDAO();
    List<PhieuMuon> listPM = new ArrayList<>();
    List<ChiTietPhieuMuon> listCTPM = new ArrayList<>();

    private void setTable() {
        modelPM = new DefaultTableModel();
        String[] colums = new String[]{
            "STT", "Ma phieu muon", "Ma sinh vien", "Ma nhan vien", "Ngay muon", "Ngay tra", "Trang thai", "Ghi chu"
        };
        modelPM.setColumnIdentifiers(colums);
        tblPhieuMuon.setModel(modelPM);
        
        modelCTPM = new DefaultTableModel();
        String[] columsCTPM = new String[]{
            "STT", "Ma phieu muon", "Ma sach", "So luong"
        };
        modelCTPM.setColumnIdentifiers(columsCTPM);
        tblCTPM.setModel(modelCTPM);
    }

    private void fillToTable() {
        listPM = pmDAO.selectAll();
        modelPM.setRowCount(0);
        int stt = 1;
        for (PhieuMuon pm : listPM) {
            modelPM.addRow(new Object[]{
                stt, pm.getMaPhieuMuon(), pm.getMaSinhVien(), pm.getMaNhanVien(), pm.getNgayMuon(), pm.getNgayTra(), pm.getNgayTra(), pm.isTrangThai(), pm.getGhiChu()
            });
            stt++;
        }
        tblPhieuMuon.setRowSelectionInterval(0, 0);
        btnFirst.setEnabled(false);
    }
    private void fillToTableCTHD(String maPM) {
        listCTPM = pmDAO.selectCTPM(maPM);
        modelCTPM.setRowCount(0);
        int stt = 1;
        for (ChiTietPhieuMuon ctpm : listCTPM) {
            modelCTPM.addRow(new Object[]{
                stt, ctpm.getMaPhieuMuon(), ctpm.getMaSach(), ctpm.getSoLuong()
            });
            stt++;
        }
        btnFirst.setEnabled(false);
    }

    private void loadForm(int index) {
        PhieuMuon pm = listPM.get(index);
        txtPhieuMuon.setText(pm.getMaPhieuMuon());
        cboMaSV.setSelectedItem(pm.getMaSinhVien());
        cboMaNV.setSelectedItem(pm.getMaNhanVien());
        txtNgayMuon.setDate(XDate.toDate(pm.getNgayMuon(), "dd/MM/yyyy"));
        txtNgayTra.setDate(XDate.toDate(pm.getNgayTra(), "dd/MM/yyyy"));
        if(pm.isTrangThai()){
            rdoChuaTra.setSelected(true);
        } else {
            rdoDaTra.setSelected(true);
        }
        txtGhiChu.setText(pm.getGhiChu());
        fillToTableCTHD(pm.getMaPhieuMuon());
    }

    private void setMaSV() {
        cboMaSV.removeAllItems();
        cboMaSV.addItem("Chon sinh vien");
        for (String masv : pmDAO.getMaSinhVien()) {
            cboMaSV.addItem(masv);
        }
    }

    private void setMaNV() {
        cboMaNV.removeAllItems();
        cboMaNV.addItem("Chon nhan vien");
        for (String manv : pmDAO.getMaNhanVien()) {
            cboMaNV.addItem(manv);
        }
    }

    private boolean isCheckForm() {
        if (txtPhieuMuon.getText().equals("")) {
            txtPhieuMuon.requestFocus();
            MsgBox.alert(this, "Chưa nhập mã phieu muon");
            return false;
        } else if (cboMaNV.getSelectedIndex() == 0 || cboMaNV.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma the loai!");
            return false;
        } else if (cboMaNV.getSelectedIndex() == 0 || cboMaNV.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma tac gia!");
            return false;
        } else if (txtNgayTra.getDate() == null) {
            MsgBox.alert(this, "Chua chon ngay tra sach");
            return false;
        } else if (txtNgayMuon.getDate() == null) {
            MsgBox.alert(this, "Chua chon ngay muon sach");
            return false;
        } else if (pmDAO.checkMaPhieuMuon(txtPhieuMuon.getText())) {
            MsgBox.alert(this, "Ma phieu muon da ton tai!");
            return false;
        } else {
            return true;
        }
    }

    private boolean isCheckFormUpdate() {
        if (txtPhieuMuon.getText().equals("")) {
            txtPhieuMuon.requestFocus();
            MsgBox.alert(this, "Chưa nhập mã phieu muon");
            return false;
        } else if (cboMaNV.getSelectedIndex() == 0 || cboMaNV.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma the loai!");
            return false;
        } else if (cboMaNV.getSelectedIndex() == 0 || cboMaNV.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma tac gia!");
            return false;
        } else if (txtNgayTra.getDate() == null) {
            MsgBox.alert(this, "Chua chon ngay tra sach");
            return false;
        } else if (txtNgayMuon.getDate() == null) {
            MsgBox.alert(this, "Chua chon ngay muon sach");
            return false;
        } else if (!pmDAO.checkMaPhieuMuon(txtPhieuMuon.getText())) {
            MsgBox.alert(this, "Ma phieu muon khong ton tai!");
            return false;
        } else {
            return true;
        }
    }

    private void insert() {
        
    }

    private void update() {
        PhieuMuon pm = new PhieuMuon(
                txtPhieuMuon.getText(),
                cboMaSV.getSelectedItem().toString(),
                cboMaNV.getSelectedItem().toString(),
                XDate.toString(txtNgayMuon.getDate(), "dd/MM/yyyy"),
                XDate.toString(txtNgayTra.getDate(), "dd/MM/yyyy"),
                txtGhiChu.getText(),
                false
        );
        try {
            pmDAO.update(pm);
            MsgBox.alert(this, "Sua thanh cong!");
            fillToTable();
        } catch (Exception e) {
            MsgBox.alert(this, "Sua that bai!");
        }
    }

    private void delete() {
        try {
            pmDAO.delete(txtPhieuMuon.getText());
            MsgBox.alert(this, "Xoa thanh cong!");
            fillToTable();
        } catch (Exception e) {
            MsgBox.alert(this, "Xoa that bai!");
        }
    }

    private void clearForm() {
        txtPhieuMuon.setText("");
        cboMaSV.setSelectedIndex(0);
        cboMaNV.setSelectedIndex(0);
        setNgayMuon();
        modelCTPM.setRowCount(0);
    }

    private void setNgayMuon() {
        Calendar cal = Calendar.getInstance(); // Lấy thời gian hiện tại
        txtNgayMuon.setDate(cal.getTime()); // Set ngày tháng năm cho dateChooser
        cal.add(Calendar.DAY_OF_MONTH, 7); // Thêm 7 ngày
        txtNgayTra.setDate(cal.getTime());
    }

    private void first() {
        tblPhieuMuon.setRowSelectionInterval(0, 0);
        onAndOff(false, true, true, true);
    }

    private void previous() {
        onAndOff(true, true, true, true);
        int max = modelPM.getRowCount();
        int index = tblPhieuMuon.getSelectedRow() - 1;
        if (index < 0) {
            tblPhieuMuon.setRowSelectionInterval(max - 1, max - 1);
            btnLast.setEnabled(false);
        } else {
            tblPhieuMuon.setRowSelectionInterval(index, index);
            if (index == 0) {
                btnFirst.setEnabled(false);
            }
        }
    }

    private void next() {
        onAndOff(true, true, true, true);
        int max = modelPM.getRowCount();
        int index = tblPhieuMuon.getSelectedRow() + 1;
        if (index == max) {
            tblPhieuMuon.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
        } else {
            tblPhieuMuon.setRowSelectionInterval(index, index);
            if (index == max - 1) {
                btnLast.setEnabled(false);
            }
        }
    }

    private void last() {
        int max = modelPM.getRowCount();
        tblPhieuMuon.setRowSelectionInterval(max - 1, max - 1);
        onAndOff(true, true, true, false);
    }

    private void onAndOff(boolean... b) {
        btnFirst.setEnabled(b[0]);
        btnPre.setEnabled(b[1]);
        btnNext.setEnabled(b[2]);
        btnLast.setEnabled(b[3]);
    }

    private void timKiem() {
        String sql = "select * from PhieuMuon where MaPhieuMuon like '%" + txtTimKiem.getText() + "%'";
        listPM = pmDAO.selectBySql(sql);
        if (!listPM.isEmpty()) {
            modelPM.setRowCount(0);
            int stt = 1;
            for (PhieuMuon pm : listPM) {
                modelPM.addRow(new Object[]{
                    stt, pm.getMaPhieuMuon(), pm.getMaSinhVien(), pm.getMaNhanVien(), pm.getNgayMuon(), pm.getNgayTra(), pm.getNgayTra(), pm.isTrangThai(), pm.getGhiChu()
                });
                stt++;
            }
            tblPhieuMuon.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
        }
    }

    private void sapXep1() {
        String sql = "SELECT * FROM TheLoaiSach ORDER BY TenTheLoai ASC";
        listPM = pmDAO.selectBySql(sql);
        if (!listPM.isEmpty()) {
            modelPM.setRowCount(0);
            int stt = 1;
            for (PhieuMuon pm : listPM) {
                modelPM.addRow(new Object[]{
                    stt, pm.getMaPhieuMuon(), pm.getMaSinhVien(), pm.getMaNhanVien(), pm.getNgayMuon(), pm.getNgayTra(), pm.getNgayTra(), pm.isTrangThai(), pm.getGhiChu()
                });
                stt++;
            }
            tblPhieuMuon.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
        }
    }

    private void sapXep2() {
        String sql = "SELECT * FROM TheLoaiSach ORDER BY TenTheLoai DESC";
        listPM = pmDAO.selectBySql(sql);
        if (!listPM.isEmpty()) {
            modelPM.setRowCount(0);
            int stt = 1;
            for (PhieuMuon pm : listPM) {
                modelPM.addRow(new Object[]{
                    stt, pm.getMaPhieuMuon(), pm.getMaSinhVien(), pm.getMaNhanVien(), pm.getNgayMuon(), pm.getNgayTra(), pm.getNgayTra(), pm.isTrangThai(), pm.getGhiChu()
                });
                stt++;
            }
            tblPhieuMuon.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
        }
    }
}
