/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ui;

import com.poly.dao.SachDAO;
import com.poly.helper.MsgBox;
import com.poly.helper.XDate;
import com.poly.helper.XImage;
import com.poly.model.NhaXuatBan;
import com.poly.model.Sach;
import com.poly.model.TacGia;
import com.poly.model.TheLoaiSach;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author thuan
 */
public class QLSachPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QLSachPanel() {
        initComponents();
        setTable();
        fillToTable();
        setComboBox();
        btnFirst.setEnabled(false);
        loadForm(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        cboSapXep = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btnNhapDS = new javax.swing.JButton();
        btnInDS = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblThongtinsach1 = new javax.swing.JLabel();
        lblMasach1 = new javax.swing.JLabel();
        lblLoaisach1 = new javax.swing.JLabel();
        lblMatacgia1 = new javax.swing.JLabel();
        lblManxb1 = new javax.swing.JLabel();
        lblNgaynhap1 = new javax.swing.JLabel();
        lblTensach1 = new javax.swing.JLabel();
        lblLink1 = new javax.swing.JLabel();
        lblSoluong1 = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        txtTensach = new javax.swing.JTextField();
        txtlink = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        cboTentheloai = new javax.swing.JComboBox<>();
        cboNXB = new javax.swing.JComboBox<>();
        cboMatacgia = new javax.swing.JComboBox<>();
        txtNgayNhap = new com.toedter.calendar.JDateChooser();
        lblHinh = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnOpenLink = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setPreferredSize(new java.awt.Dimension(600, 650));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Danh Sách Sach");
        jLabel8.setPreferredSize(new java.awt.Dimension(600, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        jPanel8.setPreferredSize(new java.awt.Dimension(380, 72));

        txtTimKiem.setPreferredSize(new java.awt.Dimension(300, 27));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/timkiem_black_24px.png"))); // NOI18N
        btnReset.setPreferredSize(new java.awt.Dimension(40, 27));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));
        jPanel9.setPreferredSize(new java.awt.Dimension(190, 72));

        cboSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mặc định", "Tên sách tăng dần", "Tên sách giảm dần" }));
        cboSapXep.setPreferredSize(new java.awt.Dimension(160, 27));
        cboSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(cboSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(575, 482));

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBang);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(585, 30));

        btnNhapDS.setText("Nhap DS");
        btnNhapDS.setPreferredSize(new java.awt.Dimension(90, 27));
        btnNhapDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDSbtnNhapDSActionPerformed(evt);
            }
        });

        btnInDS.setText("In DS");
        btnInDS.setPreferredSize(new java.awt.Dimension(90, 27));
        btnInDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInDSbtnInDSActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLast.setText(">>");
        btnLast.setPreferredSize(new java.awt.Dimension(90, 27));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastbtnLastActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNext.setText(">");
        btnNext.setPreferredSize(new java.awt.Dimension(90, 27));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextbtnNextActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPre.setText("<");
        btnPre.setPreferredSize(new java.awt.Dimension(90, 27));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrebtnPreActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFirst.setText("<<");
        btnFirst.setPreferredSize(new java.awt.Dimension(90, 27));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstbtnPreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNhapDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 650));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 650));

        lblThongtinsach1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblThongtinsach1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongtinsach1.setText("THÔNG TIN SÁCH");

        lblMasach1.setText("Mã sách");

        lblLoaisach1.setText("Ma the loai");

        lblMatacgia1.setText("Mã tác giả");

        lblManxb1.setText("Mã NXB");

        lblNgaynhap1.setText("Ngày nhập");

        lblTensach1.setText("Tên sách");

        lblLink1.setText("Link");

        lblSoluong1.setText("Số lượng");

        cboTentheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMatacgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNgayNhap.setDateFormatString("dd/MM/yyyy");

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setText("hinh");
        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        btnThem.setText("Them");
        btnThem.setPreferredSize(new java.awt.Dimension(90, 27));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnMoi.setText("Moi");
        btnMoi.setPreferredSize(new java.awt.Dimension(90, 27));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.setPreferredSize(new java.awt.Dimension(90, 27));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.setPreferredSize(new java.awt.Dimension(90, 27));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnOpenLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThongtinsach1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSoluong1)
                            .addComponent(lblMasach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLoaisach1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(lblManxb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMatacgia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTensach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNgaynhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLink1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtlink, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpenLink, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboMatacgia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTensach)
                            .addComponent(txtMasach)
                            .addComponent(cboTentheloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboNXB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongtinsach1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMasach1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTentheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoaisach1))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblManxb1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMatacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatacgia1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTensach1))
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNgaynhap1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoluong1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLink1)
                    .addComponent(btnOpenLink, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        chooseImage();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void cboSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSapXepActionPerformed
        // TODO add your handling code here:
        if (cboSapXep.getSelectedIndex() == 0 || cboSapXep.getSelectedIndex() == -1) {
            fillToTable();
        } else if (cboSapXep.getSelectedIndex() == 1) {
            String sql = "SELECT * FROM Sach ORDER BY TenSach ASC";
            sapXep(sql);
        } else if (cboSapXep.getSelectedIndex() == 2) {
            String sql = "SELECT * FROM Sach ORDER BY TenSach DESC";
            sapXep(sql);
        }
    }//GEN-LAST:event_cboSapXepActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        // TODO add your handling code here:
        int index = tblBang.getSelectedRow();
        loadForm(index);
        if (index != 0) {
            btnFirst.setEnabled(true);
        } else {
            btnFirst.setEnabled(false);
        }
        if (index != model.getRowCount() - 1) {
            btnLast.setEnabled(true);
        } else {
            btnLast.setEnabled(false);
        }
    }//GEN-LAST:event_tblBangMouseClicked

    private void btnNhapDSbtnNhapDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDSbtnNhapDSActionPerformed
        // TODO add your handling code here:
        try {
            File file = chooseExcelFile();
            if (file != null) {
                readExcelFile(file);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnNhapDSbtnNhapDSActionPerformed

    private void btnInDSbtnInDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInDSbtnInDSActionPerformed
        // TODO add your handling code here:
        String[] headers = new String[]{
            "STT", "Ma sach", "Ma the loai", "Ma tac gia", "Ma nha xuat ban", "Ten sach", "So luong", "Ngay nhap", "Hinh anh", "Link"
        };
        exportToExcel(listSach, "sach.xlsx", headers);
    }//GEN-LAST:event_btnInDSbtnInDSActionPerformed

    private void btnLastbtnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastbtnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastbtnLastActionPerformed

    private void btnNextbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextbtnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextbtnNextActionPerformed

    private void btnPrebtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrebtnPreActionPerformed
        // TODO add your handling code here:
        previous();
    }//GEN-LAST:event_btnPrebtnPreActionPerformed

    private void btnFirstbtnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstbtnPreActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstbtnPreActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (valiform()) {
            insert();
            fillToTable();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        fillToTable();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (valiformUpdate()) {
            update();
            fillToTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (txtMasach.getText().equals("")) {
            MsgBox.alert(this, "Chua nhap ma sach!");
        } else {
            if (MsgBox.confirm(this, "Ban co chac chan muon xoa?")) {
                sDAO.delete(txtMasach.getText());
                fillToTable();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnOpenLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLinkActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser("src/com/poly/pdf/");
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();
            txtlink.setText(fileName);

            try {
                Desktop.getDesktop().open(selectedFile);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnOpenLinkActionPerformed

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        if (evt.getSource() == txtTimKiem) {
            // Xử lý sự kiện khi người dùng bấm phím ở đây
            if (!txtTimKiem.getText().equals("")) {
                String sql = "select * from Sach where MaSach like '%" + txtTimKiem.getText() + "%' or TenSach like '%" + txtTimKiem.getText() + "%'";
                fillToTable(sDAO.selectBySql(sql));
            } else {
                fillToTable();
            }
        }
    }//GEN-LAST:event_txtTimKiemKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInDS;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNhapDS;
    private javax.swing.JButton btnOpenLink;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMatacgia;
    private javax.swing.JComboBox<String> cboNXB;
    private javax.swing.JComboBox<String> cboSapXep;
    private javax.swing.JComboBox<String> cboTentheloai;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblLink1;
    private javax.swing.JLabel lblLoaisach1;
    private javax.swing.JLabel lblManxb1;
    private javax.swing.JLabel lblMasach1;
    private javax.swing.JLabel lblMatacgia1;
    private javax.swing.JLabel lblNgaynhap1;
    private javax.swing.JLabel lblSoluong1;
    private javax.swing.JLabel lblTensach1;
    private javax.swing.JLabel lblThongtinsach1;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtMasach;
    private com.toedter.calendar.JDateChooser txtNgayNhap;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtlink;
    // End of variables declaration//GEN-END:variables

    DefaultTableModel model;
    SachDAO sDAO = new SachDAO();
    List<Sach> listSach;
    String newUrl;
    Calendar cal = Calendar.getInstance();// Lấy thời gian hiện tại
    Date nowDate = cal.getTime(); // Set ngày tháng năm cho dateChooser

    private void setTable() {
        model = new DefaultTableModel();
        String[] colums = new String[]{
            "STT", "Ma sach", "Ma the loai", "Ma tac gia", "Ma nha xuat ban", "Ten sach", "So luong", "Ngay nhap"
        };
        model.setColumnIdentifiers(colums);
        tblBang.setModel(model);
    }

    private void fillToTable() {
        listSach = sDAO.selectAll();
        model.setRowCount(0);
        int stt = 1;
        for (Sach s : listSach) {
            model.addRow(new Object[]{
                stt, s.getMaSach(), s.getMaTheLoai(), s.getMaTacGia(), s.getMaNhaXuatBan(), s.getTenSach(), s.getSoLuong(), s.getNgayNhap(), s.getLink()
            });
            stt++;
        }
        tblBang.setRowSelectionInterval(0, 0);
    }

    private void setComboBox() {
        cboTentheloai.removeAllItems();
        cboTentheloai.addItem("Chon ma the loai");
        for (TheLoaiSach tls : sDAO.getMaTheLoai()) {
            cboTentheloai.addItem(tls.getMaTheLoai());
        }

        cboMatacgia.removeAllItems();
        cboMatacgia.addItem("Chon ma tac gia");
        for (TacGia tg : sDAO.getMaTacGia()) {
            cboMatacgia.addItem(tg.getMaTacGia());
        }

        cboNXB.removeAllItems();
        cboNXB.addItem("Chon ma nha xuat ban");
        for (NhaXuatBan nxb : sDAO.getMaNXB()) {
            cboNXB.addItem(nxb.getMaNhaXuatBan());
        }
    }

    private void loadForm(int index) {
        Sach s = listSach.get(index);
        txtMasach.setText(s.getMaSach());
        txtTensach.setText(s.getTenSach());
        txtSoluong.setText(s.getSoLuong() + "");
        txtNgayNhap.setDate(XDate.toDate(s.getNgayNhap(), "dd/MM/yyyy"));
        cboMatacgia.setSelectedItem(s.getMaTacGia());
        cboTentheloai.setSelectedItem(s.getMaTheLoai());
        cboNXB.setSelectedItem(s.getMaNhaXuatBan());
        txtlink.setText(s.getLink());
        ImageIcon image = XImage.read(s.getHinhAnh());
        Image scaledImage = image.getImage().getScaledInstance(123, 147, Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        lblHinh.setIcon(scaledImageIcon);
        newUrl = s.getHinhAnh();
    }

    private void clearForm() {
        txtMasach.setText("");
        txtTensach.setText("");
        txtSoluong.setText("");
        txtNgayNhap.setDate(nowDate);
        cboMatacgia.setSelectedIndex(0);
        cboTentheloai.setSelectedIndex(0);
        cboNXB.setSelectedIndex(0);
        txtlink.setText("");
        lblHinh.setIcon(null);
        newUrl = "";
    }

    public boolean valiform() {
        if (txtMasach.getText().equals("")) {
            txtMasach.requestFocus();
            MsgBox.alert(this, "Chưa nhập mã sách");
            return false;
        } else if (txtTensach.getText().equals("")) {
            txtTensach.requestFocus();
            MsgBox.alert(this, "Chưa nhập Tên Sách");
            return false;
        } else if (txtSoluong.getText().equals("")) {
            MsgBox.alert(this, "Chưa nhập Số lượng");
            return false;
        } else if (cboTentheloai.getSelectedIndex() == 0 || cboTentheloai.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma the loai!");
            return false;
        } else if (cboMatacgia.getSelectedIndex() == 0 || cboMatacgia.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma tac gia!");
            return false;
        } else if (cboNXB.getSelectedIndex() == 0 || cboNXB.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma nha xuat ban!");
            return false;
        } else if (txtlink.getText().equals("")) {
            txtlink.requestFocus();
            MsgBox.alert(this, "Chưa nhập link");
            return false;
        } else if (!(txtSoluong.getText().matches("\\d{1,3}"))) {
            txtSoluong.requestFocus();
            MsgBox.alert(this, "Số lượng phải là số, lớn hơn 0");
            return false;
        } else if ((!(Integer.parseInt(txtSoluong.getText()) > 0))) {
            txtSoluong.requestFocus();
            MsgBox.alert(this, "Số lượng phải lớn hơn 0");
            return false;
        } else if (txtNgayNhap.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn Ngày nhập Sách");
            return false;
        } else if (sDAO.checkMaSach(txtMasach.getText())) {
            MsgBox.alert(this, "Ma sach da ton tai!");
            return false;
        } else {
            return true;
        }
    }

    public boolean valiformUpdate() {
        if (txtMasach.getText().equals("")) {
            txtMasach.requestFocus();
            MsgBox.alert(this, "Chưa nhập mã sách");
            return false;
        } else if (txtTensach.getText().equals("")) {
            txtTensach.requestFocus();
            MsgBox.alert(this, "Chưa nhập Tên Sách");
            return false;
        } else if (txtSoluong.getText().equals("")) {
            MsgBox.alert(this, "Chưa nhập Số lượng");
            return false;
        } else if (cboTentheloai.getSelectedIndex() == 0 || cboTentheloai.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma the loai!");
            return false;
        } else if (cboMatacgia.getSelectedIndex() == 0 || cboMatacgia.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma tac gia!");
            return false;
        } else if (cboNXB.getSelectedIndex() == 0 || cboNXB.getSelectedIndex() == -1) {
            MsgBox.alert(this, "Chua chon ma nha xuat ban!");
            return false;
        } else if (txtlink.getText().equals("")) {
            txtlink.requestFocus();
            MsgBox.alert(this, "Chưa nhập link");
            return false;
        } else if (!(txtSoluong.getText().matches("\\d{1,3}"))) {
            txtSoluong.requestFocus();
            MsgBox.alert(this, "Số lượng phải là số, lớn hơn 0");
            return false;
        } else if ((!(Integer.parseInt(txtSoluong.getText()) > 0))) {
            txtSoluong.requestFocus();
            MsgBox.alert(this, "Số lượng phải lớn hơn 0");
            return false;
        } else if (txtNgayNhap.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn Ngày nhập Sách");
            return false;
        } else if (!sDAO.checkMaSach(txtMasach.getText())) {
            MsgBox.alert(this, "Ma sach khong ton tai!");
            return false;
        } else {
            return true;
        }
    }

    private void chooseImage() {
        try {
            JFileChooser jf = new JFileChooser("D:\\Du An 1 (Quan Ly Thu Vien)\\QuanLyThuVien\\src\\com\\poly\\image");
            jf.showOpenDialog(null);
            File f = jf.getSelectedFile();
            Image img = ImageIO.read(f);
            lblHinh.setText("");
            newUrl = f.getName();
            int w = lblHinh.getWidth();
            int h = lblHinh.getHeight();
            lblHinh.setIcon(new ImageIcon(img.getScaledInstance(w, h, Image.SCALE_DEFAULT)));
            System.out.println(newUrl);
        } catch (Exception e) {
            System.out.println("ERROR");
        }
    }

    private void insert() {
        Sach s = new Sach(
                txtMasach.getText(),
                (String) cboTentheloai.getSelectedItem(),
                (String) cboMatacgia.getSelectedItem(),
                (String) cboNXB.getSelectedItem(),
                txtTensach.getText(),
                Integer.parseInt(txtSoluong.getText()),
                XDate.toString(txtNgayNhap.getDate(), "dd/MM/yyyy"),
                newUrl,
                ""
        );
        try {
            sDAO.insert(s);
            MsgBox.alert(this, "Them thanh cong!");
        } catch (Exception e) {
            MsgBox.alert(this, "Them that bai!");
        }
    }

    private void update() {
        Sach s = new Sach(
                txtMasach.getText(),
                (String) cboTentheloai.getSelectedItem(),
                (String) cboMatacgia.getSelectedItem(),
                (String) cboNXB.getSelectedItem(),
                txtTensach.getText(),
                Integer.parseInt(txtSoluong.getText()),
                XDate.toString(txtNgayNhap.getDate(), "dd/MM/yyyy"),
                newUrl,
                "ahihi"
        );
        System.out.println(s.getMaTheLoai());
        try {
            sDAO.update(s);
            MsgBox.alert(this, "Sua thanh cong!");
        } catch (Exception e) {
            MsgBox.alert(this, "Sua that bai!");
        }
    }

    private void first() {
        tblBang.setRowSelectionInterval(0, 0);
        onAndOff(false, true, true, true);
        int index = tblBang.getSelectedRow();
        loadForm(index);
    }

    private void previous() {
        onAndOff(true, true, true, true);
        int max = model.getRowCount();
        int index = tblBang.getSelectedRow() - 1;
        if (index < 0) {
            tblBang.setRowSelectionInterval(max - 1, max - 1);
            btnLast.setEnabled(false);
            loadForm(max - 1);
        } else {
            tblBang.setRowSelectionInterval(index, index);
            if (index == 0) {
                btnFirst.setEnabled(false);
            }
            loadForm(index);
        }
    }

    private void next() {
        onAndOff(true, true, true, true);
        int max = model.getRowCount();
        int index = tblBang.getSelectedRow() + 1;
        if (index == max) {
            tblBang.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
            loadForm(0);
        } else {
            tblBang.setRowSelectionInterval(index, index);
            if (index == max - 1) {
                btnLast.setEnabled(false);
            }
            loadForm(index);
        }
    }

    private void last() {
        int max = model.getRowCount();
        tblBang.setRowSelectionInterval(max - 1, max - 1);
        onAndOff(true, true, true, false);
        int index = tblBang.getSelectedRow();
        loadForm(index);
    }

    private void onAndOff(boolean... b) {
        btnFirst.setEnabled(b[0]);
        btnPre.setEnabled(b[1]);
        btnNext.setEnabled(b[2]);
        btnLast.setEnabled(b[3]);
    }

    public void exportToExcel(List<Sach> list, String fileName, String[] headers) {
        XSSFWorkbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Sach");
        int rowNum = 0;

        // Add header row
        Row headerRow = sheet.createRow(rowNum++);
        CellStyle style = sheet.getWorkbook().createCellStyle();
        Font font = sheet.getWorkbook().createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 14);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setFont(font);

        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(style);
        }

        // Add data rows
        int i = 0;
        for (Sach s : list) {
            Row row = sheet.createRow(rowNum++);
            Cell cell = row.createCell(0);
            cell.setCellValue(++i);
            cell = row.createCell(1);
            cell.setCellValue(s.getMaSach());
            cell = row.createCell(2);
            cell.setCellValue(s.getMaTheLoai());
            cell = row.createCell(3);
            cell.setCellValue(s.getMaTacGia());
            cell = row.createCell(4);
            cell.setCellValue(s.getMaNhaXuatBan());
            cell = row.createCell(5);
            cell.setCellValue(s.getTenSach());
            cell = row.createCell(6);
            cell.setCellValue(s.getSoLuong());
            cell = row.createCell(7);
            cell.setCellValue(s.getNgayNhap());
            cell = row.createCell(8);
            cell.setCellValue(s.getHinhAnh());
            cell = row.createCell(9);
            cell.setCellValue(s.getLink());
        }

        // Tạo đối tượng File tại package "com.example"
        File file = new File("src/com/poly/excel/" + fileName);

        // Ghi dữ liệu vào tệp Excel
        try ( FileOutputStream outputStream = new FileOutputStream(file)) {
            workbook.write(outputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("Excel file created: " + fileName);
    }

    public File chooseExcelFile() {
        JFileChooser fileChooser = new JFileChooser("src/com/poly/excel");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel files", "xlsx", "xls");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            return fileChooser.getSelectedFile();
        }
        return null;
    }

    public void readExcelFile(File file) throws IOException {
        FileInputStream inputStream = new FileInputStream(file);
        Workbook workbook = WorkbookFactory.create(inputStream);
        Sheet sheet = workbook.getSheetAt(0);

        int rowCount = 0;
        List<Sach> lists = new ArrayList<>();
        for (Row row : sheet) {
            // Bỏ qua dòng đầu tiên (dòng tiêu đề)
            if (rowCount == 0) {
                rowCount++;
                continue;
            }
            // Đọc dữ liệu từ các dòng còn lại
            Sach sach = new Sach();
            sach.setMaSach(row.getCell(1).getStringCellValue());
            sach.setMaTheLoai(row.getCell(2).getStringCellValue());
            sach.setMaTacGia(row.getCell(3).getStringCellValue());
            sach.setMaNhaXuatBan(row.getCell(4).getStringCellValue());
            sach.setTenSach(row.getCell(5).getStringCellValue());
            sach.setSoLuong((int) row.getCell(6).getNumericCellValue());
            sach.setNgayNhap(row.getCell(7).getStringCellValue());
            sach.setHinhAnh(row.getCell(8).getStringCellValue());
            sach.setLink(row.getCell(9).getStringCellValue());
            lists.add(sach);
        }
        workbook.close();
        inputStream.close();
    }

    private void fillToTable(List<Sach> lists) {
        model.setRowCount(0);
        if (!lists.isEmpty()) {
            int stt = 1;
            for (Sach s : lists) {
                model.addRow(new Object[]{
                    stt, s.getMaSach(), s.getMaTheLoai(), s.getMaTacGia(), s.getMaNhaXuatBan(), s.getTenSach(), s.getSoLuong(), s.getNgayNhap(), s.getLink()
                });
                stt++;
            }
            tblBang.setRowSelectionInterval(0, 0);
        }
    }

    private void sapXep(String sql) {
        listSach = sDAO.selectBySql(sql);
        if (!listSach.isEmpty()) {
            model.setRowCount(0);
            int stt = 1;
            for (Sach s : listSach) {
                model.addRow(new Object[]{
                    stt, s.getMaSach(), s.getMaTheLoai(), s.getMaTacGia(), s.getMaNhaXuatBan(), s.getTenSach(), s.getSoLuong(), s.getNgayNhap(), s.getLink()
                });
                stt++;
            }
            tblBang.setRowSelectionInterval(0, 0);
            btnFirst.setEnabled(false);
        }
    }
}
