/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import com.poly.helper.Auth;

/**
 *
 * @author hma20
 */
public class TrangChuNhanVienFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuFrame
     */
    public TrangChuNhanVienFrame() {
        initComponents();
        setLocationRelativeTo(null);
        pnlSubmenu.setVisible(false);
        cards = (CardLayout) (pnlSubmenu.getLayout());
        setClock();
        openMain(tqPanel, "Tong quan");
        setColorMenu(pnlTongQuan);
        lblUser.setText(Auth.nv.getTenNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        pnlTongQuan = new javax.swing.JPanel();
        btnTongQuan = new javax.swing.JButton();
        pnlTaoPhieuMuon = new javax.swing.JPanel();
        btnBanHang = new javax.swing.JButton();
        pnlQuanLy = new javax.swing.JPanel();
        btnQuanLy = new javax.swing.JButton();
        pnlThongKe = new javax.swing.JPanel();
        btnThongKe = new javax.swing.JButton();
        lblDateTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        pnlSubmenu = new javax.swing.JPanel();
        pnlSubquanly = new javax.swing.JPanel();
        pnlQuanLySinhVien = new javax.swing.JPanel();
        btnSinhVien = new javax.swing.JButton();
        pnlQuanLySach = new javax.swing.JPanel();
        btnSach = new javax.swing.JButton();
        pnlQuanLyTheLoaiSach = new javax.swing.JPanel();
        btnTheLoaiSach = new javax.swing.JButton();
        pnlQuanLyNXB = new javax.swing.JPanel();
        btnNXB = new javax.swing.JButton();
        pnlQuanLyTacGia = new javax.swing.JPanel();
        btnTacGia = new javax.swing.JButton();
        pnlQuanLyPhieuMuon = new javax.swing.JPanel();
        btnPhieuMuon = new javax.swing.JButton();
        pnlQuanLyNhanVien = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        pnlSubthongke = new javax.swing.JPanel();
        pnlThongKeSinhVien = new javax.swing.JPanel();
        btnTKSinhVien = new javax.swing.JButton();
        pnlThongKeSach = new javax.swing.JPanel();
        btnTKSach = new javax.swing.JButton();
        pnlThongKePhieuMuon = new javax.swing.JPanel();
        btnTKPhieuMuon = new javax.swing.JButton();
        pnlTittleBar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlDoiMK = new javax.swing.JPanel();
        btnDoiMK = new javax.swing.JButton();
        pnlGioiThieu = new javax.swing.JPanel();
        btnGioiThieu = new javax.swing.JButton();
        pnlTroGiup = new javax.swing.JPanel();
        btnTroGiup = new javax.swing.JButton();
        tbpHome = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 119, 182));
        pnlMenu.setMaximumSize(new java.awt.Dimension(200, 600));
        pnlMenu.setMinimumSize(new java.awt.Dimension(200, 600));
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 700));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/icons8_user_32px.png"))); // NOI18N
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlMenu.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 30));

        pnlTongQuan.setBackground(new java.awt.Color(0, 119, 182));
        pnlTongQuan.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlTongQuan.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTongQuan.setBackground(new java.awt.Color(28, 40, 89));
        btnTongQuan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTongQuan.setForeground(new java.awt.Color(255, 255, 255));
        btnTongQuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/trangchu_24px.png"))); // NOI18N
        btnTongQuan.setText(" Tổng quan");
        btnTongQuan.setBorder(null);
        btnTongQuan.setBorderPainted(false);
        btnTongQuan.setContentAreaFilled(false);
        btnTongQuan.setDefaultCapable(false);
        btnTongQuan.setFocusPainted(false);
        btnTongQuan.setFocusable(false);
        btnTongQuan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTongQuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTongQuanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTongQuanMouseExited(evt);
            }
        });
        btnTongQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongQuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTongQuanLayout = new javax.swing.GroupLayout(pnlTongQuan);
        pnlTongQuan.setLayout(pnlTongQuanLayout);
        pnlTongQuanLayout.setHorizontalGroup(
            pnlTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTongQuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTongQuanLayout.setVerticalGroup(
            pnlTongQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTongQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlTongQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        pnlTaoPhieuMuon.setBackground(new java.awt.Color(0, 119, 182));
        pnlTaoPhieuMuon.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlTaoPhieuMuon.setMinimumSize(new java.awt.Dimension(200, 50));

        btnBanHang.setBackground(new java.awt.Color(28, 40, 89));
        btnBanHang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/taophieumuon_24px.png"))); // NOI18N
        btnBanHang.setText("Tao Phieu Muon");
        btnBanHang.setBorder(null);
        btnBanHang.setBorderPainted(false);
        btnBanHang.setContentAreaFilled(false);
        btnBanHang.setDefaultCapable(false);
        btnBanHang.setFocusPainted(false);
        btnBanHang.setFocusable(false);
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanHangMouseExited(evt);
            }
        });
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTaoPhieuMuonLayout = new javax.swing.GroupLayout(pnlTaoPhieuMuon);
        pnlTaoPhieuMuon.setLayout(pnlTaoPhieuMuonLayout);
        pnlTaoPhieuMuonLayout.setHorizontalGroup(
            pnlTaoPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoPhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTaoPhieuMuonLayout.setVerticalGroup(
            pnlTaoPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlTaoPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, -1));

        pnlQuanLy.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLy.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLy.setMinimumSize(new java.awt.Dimension(200, 50));

        btnQuanLy.setBackground(new java.awt.Color(28, 40, 89));
        btnQuanLy.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/quanly_24px.png"))); // NOI18N
        btnQuanLy.setText(" Quản lý");
        btnQuanLy.setBorder(null);
        btnQuanLy.setBorderPainted(false);
        btnQuanLy.setContentAreaFilled(false);
        btnQuanLy.setDefaultCapable(false);
        btnQuanLy.setFocusPainted(false);
        btnQuanLy.setFocusable(false);
        btnQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanLyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanLyMouseExited(evt);
            }
        });
        btnQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyLayout = new javax.swing.GroupLayout(pnlQuanLy);
        pnlQuanLy.setLayout(pnlQuanLyLayout);
        pnlQuanLyLayout.setHorizontalGroup(
            pnlQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuanLyLayout.setVerticalGroup(
            pnlQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        pnlThongKe.setBackground(new java.awt.Color(0, 119, 182));
        pnlThongKe.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlThongKe.setMinimumSize(new java.awt.Dimension(200, 50));

        btnThongKe.setBackground(new java.awt.Color(28, 40, 89));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/thongke_24px.png"))); // NOI18N
        btnThongKe.setText(" Thống kê");
        btnThongKe.setBorder(null);
        btnThongKe.setBorderPainted(false);
        btnThongKe.setContentAreaFilled(false);
        btnThongKe.setDefaultCapable(false);
        btnThongKe.setFocusPainted(false);
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, -1));

        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTime.setText("DayTime");
        pnlMenu.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 150, 30));

        jPanel2.setBackground(new java.awt.Color(0, 119, 182));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pnlMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 420));

        btnDangXuat.setBackground(new java.awt.Color(0, 119, 182));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phieumuon_24px.png"))); // NOI18N
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 50, 30));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlSubmenu.setBackground(new java.awt.Color(0, 119, 182));
        pnlSubmenu.setMaximumSize(new java.awt.Dimension(200, 290));
        pnlSubmenu.setPreferredSize(new java.awt.Dimension(200, 360));
        pnlSubmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSubmenuMouseExited(evt);
            }
        });
        pnlSubmenu.setLayout(new java.awt.CardLayout());

        pnlSubquanly.setBackground(new java.awt.Color(0, 119, 182));
        pnlSubquanly.setMaximumSize(new java.awt.Dimension(200, 360));
        pnlSubquanly.setMinimumSize(new java.awt.Dimension(200, 360));
        pnlSubquanly.setPreferredSize(new java.awt.Dimension(200, 360));
        pnlSubquanly.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuanLySinhVien.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLySinhVien.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLySinhVien.setMinimumSize(new java.awt.Dimension(200, 50));

        btnSinhVien.setBackground(new java.awt.Color(28, 40, 89));
        btnSinhVien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSinhVien.setForeground(new java.awt.Color(255, 255, 255));
        btnSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sinhvien_24px.png"))); // NOI18N
        btnSinhVien.setText("Sinh vien");
        btnSinhVien.setBorder(null);
        btnSinhVien.setBorderPainted(false);
        btnSinhVien.setContentAreaFilled(false);
        btnSinhVien.setDefaultCapable(false);
        btnSinhVien.setFocusPainted(false);
        btnSinhVien.setFocusable(false);
        btnSinhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSinhVienMouseExited(evt);
            }
        });
        btnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLySinhVienLayout = new javax.swing.GroupLayout(pnlQuanLySinhVien);
        pnlQuanLySinhVien.setLayout(pnlQuanLySinhVienLayout);
        pnlQuanLySinhVienLayout.setHorizontalGroup(
            pnlQuanLySinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLySinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlQuanLySinhVienLayout.setVerticalGroup(
            pnlQuanLySinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLySinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        pnlQuanLySach.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLySach.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLySach.setMinimumSize(new java.awt.Dimension(200, 50));

        btnSach.setBackground(new java.awt.Color(28, 40, 89));
        btnSach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSach.setForeground(new java.awt.Color(255, 255, 255));
        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sach_24px.png"))); // NOI18N
        btnSach.setText("Sach");
        btnSach.setBorder(null);
        btnSach.setBorderPainted(false);
        btnSach.setContentAreaFilled(false);
        btnSach.setDefaultCapable(false);
        btnSach.setFocusPainted(false);
        btnSach.setFocusable(false);
        btnSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSachMouseExited(evt);
            }
        });
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLySachLayout = new javax.swing.GroupLayout(pnlQuanLySach);
        pnlQuanLySach.setLayout(pnlQuanLySachLayout);
        pnlQuanLySachLayout.setHorizontalGroup(
            pnlQuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLySachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlQuanLySachLayout.setVerticalGroup(
            pnlQuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLySach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        pnlQuanLyTheLoaiSach.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLyTheLoaiSach.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLyTheLoaiSach.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTheLoaiSach.setBackground(new java.awt.Color(28, 40, 89));
        btnTheLoaiSach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTheLoaiSach.setForeground(new java.awt.Color(255, 255, 255));
        btnTheLoaiSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/theloaisach_24px.png"))); // NOI18N
        btnTheLoaiSach.setText("The loai sach");
        btnTheLoaiSach.setBorder(null);
        btnTheLoaiSach.setBorderPainted(false);
        btnTheLoaiSach.setContentAreaFilled(false);
        btnTheLoaiSach.setDefaultCapable(false);
        btnTheLoaiSach.setFocusPainted(false);
        btnTheLoaiSach.setFocusable(false);
        btnTheLoaiSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTheLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTheLoaiSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTheLoaiSachMouseExited(evt);
            }
        });
        btnTheLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTheLoaiSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyTheLoaiSachLayout = new javax.swing.GroupLayout(pnlQuanLyTheLoaiSach);
        pnlQuanLyTheLoaiSach.setLayout(pnlQuanLyTheLoaiSachLayout);
        pnlQuanLyTheLoaiSachLayout.setHorizontalGroup(
            pnlQuanLyTheLoaiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyTheLoaiSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTheLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlQuanLyTheLoaiSachLayout.setVerticalGroup(
            pnlQuanLyTheLoaiSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTheLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLyTheLoaiSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, -1));

        pnlQuanLyNXB.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLyNXB.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLyNXB.setMinimumSize(new java.awt.Dimension(200, 50));

        btnNXB.setBackground(new java.awt.Color(28, 40, 89));
        btnNXB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNXB.setForeground(new java.awt.Color(255, 255, 255));
        btnNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhaxuatban_24px.png"))); // NOI18N
        btnNXB.setText("Nha xuat ban");
        btnNXB.setBorder(null);
        btnNXB.setBorderPainted(false);
        btnNXB.setContentAreaFilled(false);
        btnNXB.setDefaultCapable(false);
        btnNXB.setFocusPainted(false);
        btnNXB.setFocusable(false);
        btnNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNXBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNXBMouseExited(evt);
            }
        });
        btnNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyNXBLayout = new javax.swing.GroupLayout(pnlQuanLyNXB);
        pnlQuanLyNXB.setLayout(pnlQuanLyNXBLayout);
        pnlQuanLyNXBLayout.setHorizontalGroup(
            pnlQuanLyNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyNXBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlQuanLyNXBLayout.setVerticalGroup(
            pnlQuanLyNXBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNXB, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLyNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        pnlQuanLyTacGia.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLyTacGia.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLyTacGia.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTacGia.setBackground(new java.awt.Color(28, 40, 89));
        btnTacGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTacGia.setForeground(new java.awt.Color(255, 255, 255));
        btnTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/tacgia_24px.png"))); // NOI18N
        btnTacGia.setText("Tac Gia");
        btnTacGia.setBorder(null);
        btnTacGia.setBorderPainted(false);
        btnTacGia.setContentAreaFilled(false);
        btnTacGia.setDefaultCapable(false);
        btnTacGia.setFocusPainted(false);
        btnTacGia.setFocusable(false);
        btnTacGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTacGiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTacGiaMouseExited(evt);
            }
        });
        btnTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyTacGiaLayout = new javax.swing.GroupLayout(pnlQuanLyTacGia);
        pnlQuanLyTacGia.setLayout(pnlQuanLyTacGiaLayout);
        pnlQuanLyTacGiaLayout.setHorizontalGroup(
            pnlQuanLyTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyTacGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlQuanLyTacGiaLayout.setVerticalGroup(
            pnlQuanLyTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLyTacGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, -1));

        pnlQuanLyPhieuMuon.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLyPhieuMuon.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLyPhieuMuon.setMinimumSize(new java.awt.Dimension(200, 50));

        btnPhieuMuon.setBackground(new java.awt.Color(28, 40, 89));
        btnPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phieumuon_24px.png"))); // NOI18N
        btnPhieuMuon.setText("Phieu muon");
        btnPhieuMuon.setBorder(null);
        btnPhieuMuon.setBorderPainted(false);
        btnPhieuMuon.setContentAreaFilled(false);
        btnPhieuMuon.setDefaultCapable(false);
        btnPhieuMuon.setFocusPainted(false);
        btnPhieuMuon.setFocusable(false);
        btnPhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhieuMuonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhieuMuonMouseExited(evt);
            }
        });
        btnPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyPhieuMuonLayout = new javax.swing.GroupLayout(pnlQuanLyPhieuMuon);
        pnlQuanLyPhieuMuon.setLayout(pnlQuanLyPhieuMuonLayout);
        pnlQuanLyPhieuMuonLayout.setHorizontalGroup(
            pnlQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyPhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlQuanLyPhieuMuonLayout.setVerticalGroup(
            pnlQuanLyPhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLyPhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, -1));

        pnlQuanLyNhanVien.setBackground(new java.awt.Color(0, 119, 182));
        pnlQuanLyNhanVien.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlQuanLyNhanVien.setMinimumSize(new java.awt.Dimension(200, 50));

        btnNhanVien.setBackground(new java.awt.Color(28, 40, 89));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhanvien_24px.png"))); // NOI18N
        btnNhanVien.setText("Nhan vien");
        btnNhanVien.setBorder(null);
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setDefaultCapable(false);
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuanLyNhanVienLayout = new javax.swing.GroupLayout(pnlQuanLyNhanVien);
        pnlQuanLyNhanVien.setLayout(pnlQuanLyNhanVienLayout);
        pnlQuanLyNhanVienLayout.setHorizontalGroup(
            pnlQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlQuanLyNhanVienLayout.setVerticalGroup(
            pnlQuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubquanly.add(pnlQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, -1));

        pnlSubmenu.add(pnlSubquanly, "card1");

        pnlSubthongke.setBackground(new java.awt.Color(0, 119, 182));
        pnlSubthongke.setMaximumSize(new java.awt.Dimension(200, 290));
        pnlSubthongke.setMinimumSize(new java.awt.Dimension(200, 290));
        pnlSubthongke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlThongKeSinhVien.setBackground(new java.awt.Color(0, 119, 182));
        pnlThongKeSinhVien.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlThongKeSinhVien.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTKSinhVien.setBackground(new java.awt.Color(28, 40, 89));
        btnTKSinhVien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTKSinhVien.setForeground(new java.awt.Color(255, 255, 255));
        btnTKSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sinhvien_24px.png"))); // NOI18N
        btnTKSinhVien.setText("Sinh vien");
        btnTKSinhVien.setBorder(null);
        btnTKSinhVien.setBorderPainted(false);
        btnTKSinhVien.setContentAreaFilled(false);
        btnTKSinhVien.setDefaultCapable(false);
        btnTKSinhVien.setFocusPainted(false);
        btnTKSinhVien.setFocusable(false);
        btnTKSinhVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTKSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTKSinhVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKSinhVienMouseExited(evt);
            }
        });
        btnTKSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSinhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeSinhVienLayout = new javax.swing.GroupLayout(pnlThongKeSinhVien);
        pnlThongKeSinhVien.setLayout(pnlThongKeSinhVienLayout);
        pnlThongKeSinhVienLayout.setHorizontalGroup(
            pnlThongKeSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeSinhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTKSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlThongKeSinhVienLayout.setVerticalGroup(
            pnlThongKeSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTKSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubthongke.add(pnlThongKeSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        pnlThongKeSach.setBackground(new java.awt.Color(0, 119, 182));
        pnlThongKeSach.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlThongKeSach.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTKSach.setBackground(new java.awt.Color(28, 40, 89));
        btnTKSach.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTKSach.setForeground(new java.awt.Color(255, 255, 255));
        btnTKSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/sach_24px.png"))); // NOI18N
        btnTKSach.setText("Sach");
        btnTKSach.setBorder(null);
        btnTKSach.setBorderPainted(false);
        btnTKSach.setContentAreaFilled(false);
        btnTKSach.setDefaultCapable(false);
        btnTKSach.setFocusPainted(false);
        btnTKSach.setFocusable(false);
        btnTKSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTKSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTKSachMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKSachMouseExited(evt);
            }
        });
        btnTKSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKeSachLayout = new javax.swing.GroupLayout(pnlThongKeSach);
        pnlThongKeSach.setLayout(pnlThongKeSachLayout);
        pnlThongKeSachLayout.setHorizontalGroup(
            pnlThongKeSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKeSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTKSach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlThongKeSachLayout.setVerticalGroup(
            pnlThongKeSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTKSach, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubthongke.add(pnlThongKeSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        pnlThongKePhieuMuon.setBackground(new java.awt.Color(0, 119, 182));
        pnlThongKePhieuMuon.setMaximumSize(new java.awt.Dimension(200, 50));
        pnlThongKePhieuMuon.setMinimumSize(new java.awt.Dimension(200, 50));

        btnTKPhieuMuon.setBackground(new java.awt.Color(28, 40, 89));
        btnTKPhieuMuon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTKPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnTKPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/phieumuon_24px.png"))); // NOI18N
        btnTKPhieuMuon.setText("Phieu muon");
        btnTKPhieuMuon.setBorder(null);
        btnTKPhieuMuon.setBorderPainted(false);
        btnTKPhieuMuon.setContentAreaFilled(false);
        btnTKPhieuMuon.setDefaultCapable(false);
        btnTKPhieuMuon.setFocusPainted(false);
        btnTKPhieuMuon.setFocusable(false);
        btnTKPhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTKPhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTKPhieuMuonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKPhieuMuonMouseExited(evt);
            }
        });
        btnTKPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPhieuMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongKePhieuMuonLayout = new javax.swing.GroupLayout(pnlThongKePhieuMuon);
        pnlThongKePhieuMuon.setLayout(pnlThongKePhieuMuonLayout);
        pnlThongKePhieuMuonLayout.setHorizontalGroup(
            pnlThongKePhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongKePhieuMuonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTKPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlThongKePhieuMuonLayout.setVerticalGroup(
            pnlThongKePhieuMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTKPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlSubthongke.add(pnlThongKePhieuMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, -1));

        pnlSubmenu.add(pnlSubthongke, "card2");

        getContentPane().add(pnlSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, 350));

        pnlTittleBar.setBackground(new java.awt.Color(0, 119, 182));
        pnlTittleBar.setMaximumSize(new java.awt.Dimension(1000, 36));
        pnlTittleBar.setMinimumSize(new java.awt.Dimension(1000, 36));
        pnlTittleBar.setPreferredSize(new java.awt.Dimension(1000, 50));
        pnlTittleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Tong quan");
        pnlTittleBar.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 210, 40));

        pnlDoiMK.setBackground(new java.awt.Color(0, 119, 182));

        btnDoiMK.setBackground(new java.awt.Color(0, 119, 182));
        btnDoiMK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhaxuatban_24px.png"))); // NOI18N
        btnDoiMK.setText("Doi mat khau");
        btnDoiMK.setBorder(null);
        btnDoiMK.setBorderPainted(false);
        btnDoiMK.setContentAreaFilled(false);
        btnDoiMK.setDefaultCapable(false);
        btnDoiMK.setFocusPainted(false);
        btnDoiMK.setFocusable(false);
        btnDoiMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoiMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoiMKMouseExited(evt);
            }
        });
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDoiMKLayout = new javax.swing.GroupLayout(pnlDoiMK);
        pnlDoiMK.setLayout(pnlDoiMKLayout);
        pnlDoiMKLayout.setHorizontalGroup(
            pnlDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoiMKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoiMK)
                .addContainerGap())
        );
        pnlDoiMKLayout.setVerticalGroup(
            pnlDoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDoiMKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlTittleBar.add(pnlDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 0, -1, 50));

        pnlGioiThieu.setBackground(new java.awt.Color(0, 119, 182));

        btnGioiThieu.setBackground(new java.awt.Color(0, 119, 182));
        btnGioiThieu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhaxuatban_24px.png"))); // NOI18N
        btnGioiThieu.setText("Gioi Thieu");
        btnGioiThieu.setBorder(null);
        btnGioiThieu.setBorderPainted(false);
        btnGioiThieu.setContentAreaFilled(false);
        btnGioiThieu.setDefaultCapable(false);
        btnGioiThieu.setFocusPainted(false);
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGioiThieuMouseExited(evt);
            }
        });
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGioiThieuLayout = new javax.swing.GroupLayout(pnlGioiThieu);
        pnlGioiThieu.setLayout(pnlGioiThieuLayout);
        pnlGioiThieuLayout.setHorizontalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGioiThieuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlGioiThieuLayout.setVerticalGroup(
            pnlGioiThieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGioiThieuLayout.createSequentialGroup()
                .addComponent(btnGioiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlTittleBar.add(pnlGioiThieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 142, 50));

        pnlTroGiup.setBackground(new java.awt.Color(0, 119, 182));

        btnTroGiup.setBackground(new java.awt.Color(0, 119, 182));
        btnTroGiup.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTroGiup.setForeground(new java.awt.Color(255, 255, 255));
        btnTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhaxuatban_24px.png"))); // NOI18N
        btnTroGiup.setText("Tro giup");
        btnTroGiup.setBorder(null);
        btnTroGiup.setBorderPainted(false);
        btnTroGiup.setContentAreaFilled(false);
        btnTroGiup.setDefaultCapable(false);
        btnTroGiup.setFocusPainted(false);
        btnTroGiup.setFocusable(false);
        btnTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTroGiupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTroGiupMouseExited(evt);
            }
        });
        btnTroGiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroGiupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTroGiupLayout = new javax.swing.GroupLayout(pnlTroGiup);
        pnlTroGiup.setLayout(pnlTroGiupLayout);
        pnlTroGiupLayout.setHorizontalGroup(
            pnlTroGiupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTroGiupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTroGiup, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTroGiupLayout.setVerticalGroup(
            pnlTroGiupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTroGiupLayout.createSequentialGroup()
                .addComponent(btnTroGiup, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlTittleBar.add(pnlTroGiup, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 130, 50));

        getContentPane().add(pnlTittleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 50));

        tbpHome.setBackground(new java.awt.Color(255, 255, 255));
        tbpHome.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tbpHome.setPreferredSize(new java.awt.Dimension(1050, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 650));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        tbpHome.addTab("tab1", jPanel1);

        getContentPane().add(tbpHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTongQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongQuanActionPerformed
        // TODO add your handling code here:
        openMain(tqPanel, "Tong quan");
        setColorMenu(pnlTongQuan);
    }//GEN-LAST:event_btnTongQuanActionPerformed

    private void btnTongQuanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTongQuanMouseEntered
        // TODO add your handling code here:
        hover(true, pnlTongQuan);
        pnlSubmenu.setVisible(false);
        checkColor();
    }//GEN-LAST:event_btnTongQuanMouseEntered

    private void btnTongQuanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTongQuanMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().equals("Tong quan")){
            setColorMenu(pnlTongQuan);
        } else {
            hover(false, pnlTongQuan);
            pnlSubmenu.setVisible(false);
        }
    }//GEN-LAST:event_btnTongQuanMouseExited

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        openMain(tpmPanel, "Tao phieu muon");
        setColorMenu(pnlTaoPhieuMuon);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseEntered
        // TODO add your handling code here:
        hover(true, pnlTaoPhieuMuon);
        pnlSubmenu.setVisible(false);
        checkColor();
    }//GEN-LAST:event_btnBanHangMouseEntered

    private void btnBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().equals("Tao phieu muon")){
            setColorMenu(pnlTaoPhieuMuon);
        } else {
            hover(false, pnlTaoPhieuMuon);
            pnlSubmenu.setVisible(false);
        }
    }//GEN-LAST:event_btnBanHangMouseExited

    private void btnQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyActionPerformed
        // TODO add your handling code here:
        pnlSubmenu.setVisible(true);
        setColorMenu(pnlQuanLy);
        cards.show(pnlSubmenu, "card1");
    }//GEN-LAST:event_btnQuanLyActionPerformed

    private void btnQuanLyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLy);
        hoverCard(true,1);
        checkColor();
    }//GEN-LAST:event_btnQuanLyMouseEntered

    private void btnQuanLyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().startsWith("Quan ly")){
            setColorMenu(pnlQuanLy);
        } else {
            hover(false, pnlQuanLy);
            setColorMenu(jPanel1);
        }
    }//GEN-LAST:event_btnQuanLyMouseExited

    private void btnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhVienActionPerformed
        // TODO add your handling code here:
        openMain(qlsvPanel, "Quan ly sinh vien");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnSinhVienActionPerformed

    private void btnSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinhVienMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLySinhVien);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnSinhVienMouseEntered

    private void btnSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinhVienMouseExited
        // TODO add your handling code here:
        hover(false, pnlQuanLySinhVien);
        hoverCard(false,1);
    }//GEN-LAST:event_btnSinhVienMouseExited

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSachActionPerformed
        // TODO add your handling code here:
        openMain(qlsPanel, "Quan ly sach");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnSachActionPerformed

    private void btnSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSachMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLySach);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnSachMouseEntered

    private void btnSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSachMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().equals("Quan ly sach")){
            setColorMenu(pnlQuanLy);
        } else {
            hover(false, pnlQuanLySach);
            checkColor();
        }
    }//GEN-LAST:event_btnSachMouseExited

    private void btnTheLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTheLoaiSachActionPerformed
        // TODO add your handling code here:
        openMain(qltlPanel,"Quan ly the loai");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTheLoaiSachActionPerformed

    private void btnTheLoaiSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTheLoaiSachMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLyTheLoaiSach);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnTheLoaiSachMouseEntered

    private void btnTheLoaiSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTheLoaiSachMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().equals("Quan ly the loai")){
            setColorMenu(pnlQuanLy);
        } else {
            hover(false, pnlQuanLyTheLoaiSach);
            setColorMenu(jPanel1);
        }
    }//GEN-LAST:event_btnTheLoaiSachMouseExited

    private void btnNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNXBActionPerformed
        // TODO add your handling code here:
        openMain(qlnxbPanel, "Quan ly nha xuat ban");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnNXBActionPerformed

    private void btnNXBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNXBMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLyNXB);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnNXBMouseEntered

    private void btnNXBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNXBMouseExited
        // TODO add your handling code here:
        hover(false, pnlQuanLyNXB);
    }//GEN-LAST:event_btnNXBMouseExited

    private void btnTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacGiaActionPerformed
        // TODO add your handling code here:
        openMain(qltgPanel, "Quan ly tac gia");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTacGiaActionPerformed

    private void btnTacGiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTacGiaMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLyTacGia);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnTacGiaMouseEntered

    private void btnTacGiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTacGiaMouseExited
        // TODO add your handling code here:
        hover(false, pnlQuanLyTacGia);
    }//GEN-LAST:event_btnTacGiaMouseExited

    private void btnPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMuonActionPerformed
        // TODO add your handling code here:
        openMain(qlpmPanel, "Quan ly phieu muon");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnPhieuMuonActionPerformed

    private void btnPhieuMuonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhieuMuonMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLyPhieuMuon);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnPhieuMuonMouseEntered

    private void btnPhieuMuonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhieuMuonMouseExited
        // TODO add your handling code here:
        hover(false, pnlQuanLyPhieuMuon);
    }//GEN-LAST:event_btnPhieuMuonMouseExited

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        openMain(qlnvPanel, "Quan ly nhan vien");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        hover(true, pnlQuanLyNhanVien);
        hoverCard(true, 1);
        checkColor();
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        hover(false, pnlQuanLyNhanVien);
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        pnlSubmenu.setVisible(true);
        setColorMenu(pnlThongKe);
        cards.show(pnlSubmenu, "card2");
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseEntered
        // TODO add your handling code here:
        hover(true, pnlThongKe);
        hoverCard(true,2);
        checkColor();
    }//GEN-LAST:event_btnThongKeMouseEntered

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        // TODO add your handling code here:
        if(lblTitle.getText().startsWith("Thong ke")){
            setColorMenu(pnlQuanLy);
        } else {
            hover(false, pnlThongKe);
            setColorMenu(jPanel1);
        }
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnTKSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSinhVienActionPerformed
        // TODO add your handling code here:
        openMain(tksvPanel, "Thong ke sinh vien");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTKSinhVienActionPerformed

    private void btnTKSinhVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKSinhVienMouseEntered
        // TODO add your handling code here:
        hover(true, pnlThongKeSinhVien);
        hoverCard(true,2);
        checkColor();
    }//GEN-LAST:event_btnTKSinhVienMouseEntered

    private void btnTKSinhVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKSinhVienMouseExited
        // TODO add your handling code here:
        hover(false, pnlThongKeSinhVien);
    }//GEN-LAST:event_btnTKSinhVienMouseExited

    private void btnTKSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSachActionPerformed
        // TODO add your handling code here:
        openMain(tksPanel, "Thong ke sach");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTKSachActionPerformed

    private void btnTKSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKSachMouseEntered
        // TODO add your handling code here:
        hover(true, pnlThongKeSach);
        hoverCard(true,2);
        checkColor();
    }//GEN-LAST:event_btnTKSachMouseEntered

    private void btnTKSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKSachMouseExited
        // TODO add your handling code here:
        hover(false, pnlThongKeSach);
    }//GEN-LAST:event_btnTKSachMouseExited

    private void btnTKPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPhieuMuonActionPerformed
        // TODO add your handling code here:
        openMain(tkpmPanel, "Thong ke phieu muon");
        setColorMenu(pnlQuanLy);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTKPhieuMuonActionPerformed

    private void btnTKPhieuMuonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPhieuMuonMouseEntered
        // TODO add your handling code here:
        hover(true, pnlThongKePhieuMuon);
        hoverCard(true,2);
        checkColor();
    }//GEN-LAST:event_btnTKPhieuMuonMouseEntered

    private void btnTKPhieuMuonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPhieuMuonMouseExited
        // TODO add your handling code here:
        hover(false, pnlThongKePhieuMuon);
    }//GEN-LAST:event_btnTKPhieuMuonMouseExited

    private void pnlSubmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSubmenuMouseExited
        // TODO add your handling code here:
        checkColor();
        pnlQuanLy.setBackground(no);
        pnlThongKe.setBackground(no);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_pnlSubmenuMouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        pnlSubmenu.setVisible(false);
        checkColor();
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        pnlSubmenu.setVisible(false);
        checkColor();
    }//GEN-LAST:event_jPanel2MouseExited

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangNhapFrame dn = new DangNhapFrame();
        dn.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void btnGioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGioiThieuMouseEntered
        // TODO add your handling code here:
        hover(true, pnlGioiThieu);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnGioiThieuMouseEntered

    private void btnGioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGioiThieuMouseExited
        // TODO add your handling code here:
        hover(false, pnlGioiThieu);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnGioiThieuMouseExited

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DoiMatKhauFrame dmk = new DoiMatKhauFrame();
        dmk.setVisible(true);
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void btnDoiMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMKMouseEntered
        // TODO add your handling code here:
        hover(true, pnlDoiMK);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnDoiMKMouseEntered

    private void btnDoiMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMKMouseExited
        // TODO add your handling code here:
        hover(false, pnlDoiMK);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnDoiMKMouseExited

    private void btnTroGiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroGiupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTroGiupActionPerformed

    private void btnTroGiupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTroGiupMouseEntered
        // TODO add your handling code here:
        hover(true, pnlTroGiup);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTroGiupMouseEntered

    private void btnTroGiupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTroGiupMouseExited
        // TODO add your handling code here:
        hover(false, pnlTroGiup);
        pnlSubmenu.setVisible(false);
    }//GEN-LAST:event_btnTroGiupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuNhanVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnNXB;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuMuon;
    private javax.swing.JButton btnQuanLy;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnSinhVien;
    private javax.swing.JButton btnTKPhieuMuon;
    private javax.swing.JButton btnTKSach;
    private javax.swing.JButton btnTKSinhVien;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnTheLoaiSach;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTongQuan;
    private javax.swing.JButton btnTroGiup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlDoiMK;
    private javax.swing.JPanel pnlGioiThieu;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlQuanLy;
    private javax.swing.JPanel pnlQuanLyNXB;
    private javax.swing.JPanel pnlQuanLyNhanVien;
    private javax.swing.JPanel pnlQuanLyPhieuMuon;
    private javax.swing.JPanel pnlQuanLySach;
    private javax.swing.JPanel pnlQuanLySinhVien;
    private javax.swing.JPanel pnlQuanLyTacGia;
    private javax.swing.JPanel pnlQuanLyTheLoaiSach;
    private javax.swing.JPanel pnlSubmenu;
    private javax.swing.JPanel pnlSubquanly;
    private javax.swing.JPanel pnlSubthongke;
    private javax.swing.JPanel pnlTaoPhieuMuon;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JPanel pnlThongKePhieuMuon;
    private javax.swing.JPanel pnlThongKeSach;
    private javax.swing.JPanel pnlThongKeSinhVien;
    private javax.swing.JPanel pnlTittleBar;
    private javax.swing.JPanel pnlTongQuan;
    private javax.swing.JPanel pnlTroGiup;
    private javax.swing.JTabbedPane tbpHome;
    // End of variables declaration//GEN-END:variables

    CardLayout cards;
    Timer clock;
    Color no = new Color(0,119,182);
    Color yes = new Color(96,177,255);
    TongQuanPanel tqPanel = new TongQuanPanel();
    TaoPhieuMuonPanel tpmPanel = new TaoPhieuMuonPanel();
    QLSinhVienPanel qlsvPanel = new QLSinhVienPanel();
    QLNhanVienPanel qlnvPanel = new QLNhanVienPanel();
    QLSachPanel qlsPanel = new QLSachPanel();
    QLTacGiaPanel qltgPanel = new QLTacGiaPanel();
    QLTheLoaiPanel qltlPanel = new QLTheLoaiPanel();
    QLNhaXuatBan qlnxbPanel = new QLNhaXuatBan();
    QLPhieuMuonPanel qlpmPanel = new QLPhieuMuonPanel();
    TKPhieuMuonPanel tkpmPanel = new TKPhieuMuonPanel();
    TKSachPanel tksPanel = new TKSachPanel();
    TKSinhVienPanel tksvPanel = new TKSinhVienPanel();
    

    private void setClock() {
        clock = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy - hh:mm:ss aa");
                Date day = new Date();
                String time = sdf.format(day);
                lblDateTime.setText(time);
            }
        });
        clock.start();
    }
    
    private void setColorMenu(JPanel panel){
        JPanel[] panels = new JPanel[]{
            pnlTongQuan,
            pnlTaoPhieuMuon,
            pnlQuanLy,
            pnlThongKe,
            pnlDoiMK,
            pnlTroGiup,
            pnlGioiThieu
        };
        for (int i = 0; i < panels.length; i++) {
            if(panel == panels[i]){
                panels[i].setBackground(yes);
            } else {
                panels[i].setBackground(no);
            }
        }
    }
    
    private void openMain(JPanel panel, String title) {
        tbpHome.removeAll();
        tbpHome.addTab("tab 1",panel);
        lblTitle.setText(title);
        tbpHome.setSelectedComponent(panel);
    }
    
    private void hover(boolean isHover, JPanel panel){
        if(isHover){
            panel.setBackground(yes);
        } else {
            panel.setBackground(no);
        }
    }
    
    private void hoverCard(boolean isHover, int index){
        
        pnlSubmenu.setVisible(isHover);
        if(index == 1){
            setColorMenu(pnlQuanLy);
            cards.show(pnlSubmenu, "card1");
        } else if(index==2) {
            setColorMenu(pnlThongKe);
            cards.show(pnlSubmenu, "card2");
        }
    }
    
    private void checkColor(){
        if(lblTitle.getText().startsWith("Thong ke")){
            pnlThongKe.setBackground(yes);
        } else if(lblTitle.getText().startsWith("Quan ly")){
            pnlQuanLy.setBackground(yes);
        } else if(lblTitle.getText().equals("Tong quan")){
            pnlTongQuan.setBackground(yes);
        } else if(lblTitle.getText().equals("Tao phieu muon")){
            pnlTaoPhieuMuon.setBackground(yes);
        } else {
            setColorMenu(jPanel1);
        }
    }
    
}
